In [12]:
#Perceptron using class structure
#'n_inputs' inputs, 
#'n_inputs' synapses, 
#1 neuron, 
#1 layer
#1 output
# All neurons use linear regression

In [131]:
import numpy as np

class NeuralNetwork():
    def __init__(self, n_inputs):
        #initialize synaptic weights
        np.random.seed()
        self.synaptic_weights = 2* np.random.random((n_inputs,1)) -1
        self.final_outputs =[]
        
    def sigmoid(self, x):
        return 1/ (1+ np.exp(-x))

    def sigmoid_derivative(self, x):
        return np.exp(-x) / pow(1+np.exp(-x),2)
        
    def train(self, training_inputs, training_outputs, training_iterations):
        for i in range(training_iterations):  
            outputs = self.think(training_inputs)
            error = training_outputs - outputs
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(outputs))
            
            cost = self.cost_function(training_outputs, outputs)
            cost_grads = self.cost_gradient_function(training_outputs, outputs, training_inputs)
            print "cost_grads.T: "
            print cost_grads.T
            print "adjustments: "
            print adjustments
            print "cost_grads * error: "
            print cost_grads.shape
            print "\n"
            
            self.synaptic_weights +=adjustments
        self.final_outputs = outputs
        return 0

    def think(self, inputs):
        #LIN.REG.: outputs = sum(x_0*w_0 + x_1*w_1 +...+ x_n*w_n) where n = n_inputs
        inputs = inputs.astype(float)
        outputs = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return outputs
    
    def cost_function(self, training_outputs, hypothesised_outputs):
        #SUM OF SQUARES
        return np.sum(pow(training_outputs - hypothesised_outputs ,2))

    def cost_gradient_function(self, training_outputs, hypothesised_outputs, training_inputs):
        cost_grad = -1*(training_outputs - hypothesised_outputs)*training_inputs
        cost_grads = []
        for i in cost_grad.T:
            cost_grads.append(np.sum(i))
        return np.asarray(cost_grads)


In [132]:
#Example 1 - 3 input variables

#Define training inputs and outputs
training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

n_inputs=len(training_inputs[0])

neural_network = NeuralNetwork(n_inputs)


print "Initial random synaptic_weights: "
print(neural_network.synaptic_weights)

print "\n----------\n"
neural_network.train(training_inputs, training_outputs, 2)

print "\n----------\n"
print "\nSynaptic weights after training: "
print neural_network.synaptic_weights

print "\nOutputs after training: "
print neural_network.final_outputs

Initial random synaptic_weights: 
[[-0.02693742]
 [-0.53681492]
 [ 0.01173835]]

----------

cost_grads.T: 
[-1.13840242 -0.2629368  -0.26380194]
adjustments: 
[[0.27197539]
 [0.06369059]
 [0.06408889]]
cost_grads * error: 
(3,)


cost_grads.T: 
[-0.95845632 -0.1360295  -0.03754667]
adjustments: 
[[0.22433012]
 [0.03103028]
 [0.00641215]]
cost_grads * error: 
(3,)



----------


Synaptic weights after training: 
[[ 0.46936809]
 [-0.44209405]
 [ 0.08223939]]

Outputs after training: 
[[0.51894773]
 [0.46200859]
 [0.5795351 ]
 [0.40196192]]


In [52]:
#Example 2 - 4 input variables, larger dataset (m=8)

#Define training inputs and outputs
training_inputs = np.array([[1,0,0,1],
                           [1,1,1,1],
                           [1,1,0,1],
                           [1,0,1,1],
                           [1,0,0,0],
                           [1,1,0,0],
                           [1,0,1,0],
                           [1,1,1,0]])

training_outputs = np.array([[0,1,1,0,0,1,0,1]]).T

n_inputs=len(training_inputs[0])
neural_network = NeuralNetwork(n_inputs)

print "Initial random synaptic_weights: "
print(neural_network.synaptic_weights)


neural_network.train(training_inputs, training_outputs, 20000)

print "\nSynaptic weights after training: "
print neural_network.synaptic_weights

print "\nOutputs after training: "
print neural_network.final_outputs

print "\n"
for i in neural_network.final_outputs:
    if float(i[0]) > .99:
        i[0] == 1.
        print "1"
    elif float(i[0]) < 0.01:
        i[0] == 0.
        print "0"
    else:
        print i[0]


Initial random synaptic_weights: 
[[ 0.65537092]
 [-0.43519054]
 [-0.5528945 ]
 [-0.41253608]]

Synaptic weights after training: 
[[-8.43818084]
 [17.85545618]
 [-0.4066965 ]
 [-0.40669069]]

Outputs after training: 
[[1.44105396e-04]
 [9.99816633e-01]
 [9.99877898e-01]
 [9.59566523e-05]
 [2.16407536e-04]
 [9.99918695e-01]
 [1.44104559e-04]
 [9.99877898e-01]]


0
1
1
0
0
1
0
1
